---
- name: "Import variables tasks."
  ansible.builtin.import_tasks: "set_vars.yml"

- name: "Import NetworkManager configuration."
  ansible.builtin.import_tasks: "configure-nm.yml"

- name: "Create configuration directory."
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: "directory"
  loop:
    - "/etc/rancher"
    - "/etc/rancher/rke2"

- name: "Copy RKE2 configuration."
  become: true
  ansible.builtin.template:
    src: "config-{{ rke2_install_type }}.yaml.j2"
    dest: "/etc/rancher/rke2/config.yaml"
    mode: "0640"
  notify:
    - "Set service state."

- name: "Import version determination."
  ansible.builtin.import_tasks: "determine-version.yml"

- name: "Install via rpm package."
  when: "rke2_install_method == 'rpm'"
  ansible.builtin.include_tasks: "install-rpm.yml"

- name: "Install via tar archive."
  when: "rke2_install_method == 'tar'"
  ansible.builtin.include_tasks: "install-tar.yml"

- name: "Setup fapolicy rules."
  when:
    - "rke2_install_skip_fapolicy | bool"
    - "ansible_os_family == 'RedHat'"
  ansible.builtin.include_tasks: "setup-fapolicy.yml"

- name: "Flush handlers."
  ansible.builtin.meta: "flush_handlers"
