---
- name: "Set platform/version specific variables."
  ansible.builtin.include_vars: "{{ __rke2_vars_file }}"
  loop: "{{ __rke2_vars_file_list }}"
  vars:
    __rke2_vars_file_list:
      - "OS-{{ ansible_facts['os_family'] }}.yml"
      - "OS-{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
      - "D-{{ ansible_facts['distribution'] }}.yml"
      - "D-{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
      - "D-{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"
    __rke2_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: "__rke2_vars_file is file"

- name: "Add control-plane workload taint."
  when:
    - "rke2_install_type == 'server'"
    - "not rke2_server_allow_workload"
  ansible.builtin.set_fact:
    rke2_node_taints: "{{ rke2_node_taints | default([]) + ['CriticalAddonsOnly=true:NoExecute'] }}"

- name: "Disable built-in CoreDNS deployment."
  when: "not rke2_server_coredns_enabled"
  ansible.builtin.set_fact:
    __rke2_server_disabled_components: "{{ __rke2_server_disabled_components + ['rke2-coredns'] }}"

- name: "Disable built-in Ingress Nginx deployment."
  when: "not rke2_server_ingress_nginx_enabled"
  ansible.builtin.set_fact:
    __rke2_server_disabled_components: "{{ __rke2_server_disabled_components + ['rke2-ingress-nginx'] }}"

- name: "Disable built-in Metrics Server deployment."
  when: "not rke2_server_metrics_server_enabled"
  ansible.builtin.set_fact:
    __rke2_server_disabled_components: "{{ __rke2_server_disabled_components + ['rke2-metrics-server'] }}"
