---
- name: "Restart fapolicyd."
  become: true
  ansible.builtin.service:
    name: "fapolicyd"
    state: "restarted"

- name: "Set service state."
  become: true
  ansible.builtin.service:
    name: "rke2-{{ rke2_install_type }}"
    enabled: "{{ rke2_service_enabled }}"
    state: "{{ 'restarted' if rke2_service_started else 'stopped' }}"

- name: "Restart NetworkManager."
  become: true
  ansible.builtin.service:
    name: "NetworkManager"
    state: "restarted"
